// usuario
POST https://labook-back-end.herokuapp.com/user/signup
Content-Type: application/json

{
   "name":"ADM",
   "email":"ADM@gmail.com",
   "password":"jaja12",
   "roles":"ADIMIN"
}

###
# @name login
POST  https://labook-back-end.herokuapp.com/user/login
Content-Type: application/json

{
   "email":"ma@gmail.com",
   "password":"jaja12"
}

### POST -------------------------------------------------
// create
POST  https://labook-back-end.herokuapp.com/post/create
Authorization: {{login.response.body.Token}}
Content-Type: application/json

{
   "content":"labenuuuu"
}

###
//get post by id
GET  https://labook-back-end.herokuapp.com/post/f5e32ce6-4824-4c5f-9077-760bad836517
Authorization: {{login.response.body.Token}}

###

GET  https://labook-back-end.herokuapp.com/post/feed
Authorization: {{login.response.body.Token}}
###


DELETE   https://labook-back-end.herokuapp.com/post/delete/8c4c0f0f-a09e-4001-ae7d-e5599a26f2c0
Authorization: {{login.response.body.Token}}

### Likes -----------------------------------------------------------
POST    https://labook-back-end.herokuapp.com/posts/like
Content-Type: application/json

{
   "id":"054e7163-881d-4765-ae49-9d2f2f60aa5a",
   "token":"{{login.response.body.Token}}"
}

###
DELETE  https://labook-back-end.herokuapp.com/posts/dislike/054e7163-881d-4765-ae49-9d2f2f60aa5a
Authorization: Authorization: {{login.response.body.Token}}



### Friends --------------------------------------------------------------
// cria nova amizade 
POST   https://labook-back-end.herokuapp.com/friends/done
Content-Type: application/json

{
   "token":"{{login.response.body.Token}}",
   "id":"614b7316-bc86-463b-82d8-8ff98159a58b"
}

### 
// deleta amizade
DELETE    https://labook-back-end.herokuapp.com/friends/undone/614b7316-bc86-463b-82d8-8ff98159a58b
Authorization: {{login.response.body.Token}}